spring:
    datasource:
        password: "711418aa"
        url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: "root"
    thymeleaf:
        prefix: classpath:/templates/
        servlet:
            content-type: text/html
        suffix: .html
        encoding: UTF-8
    mail:
        # 163
        host: smtp.163.com
        port: 
        username: w2569893@163.com
        password: 711418aa*
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.socketFactory.port: 465
            mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
            mail.smtp.socketFactory.fallback: false
springdatasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    type-aliases-package: com.demo.demo
springboot:
    datasource:
        type: com.alibaba.druid.pool.DruidDataScource
